# Generated by Django 5.0.1 on 2026-01-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('image', models.URLField(max_length=500)),
                ('message', models.TextField()),
                ('path', models.CharField(help_text='Frontend route path', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Management Member',
                'verbose_name_plural': 'Management Members',
                'db_table': 'management_members',
                'ordering': ['order', 'name'],
            },
        ),
    ]
